# Generated by Django 3.0.6 on 2020-05-19 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermsAutoField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=255, verbose_name='Perm Label')),
            ],
            options={
                'db_table': 'perms_auto_field',
            },
        ),
        migrations.CreateModel(
            name='PermsUUIDField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=255, verbose_name='Perm Label')),
            ],
            options={
                'db_table': 'perms_uuid_field',
            },
        ),
        migrations.CreateModel(
            name='UserUUIDField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=255, verbose_name='First Name')),
                ('perms_uuid_field', models.ManyToManyField(to='sample_app.PermsUUIDField', verbose_name='Permissions')),
            ],
            options={
                'db_table': 'user_uuid_field',
            },
        ),
        migrations.CreateModel(
            name='UserAutoField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=255, verbose_name='First Name')),
                ('perms_auto_field', models.ManyToManyField(to='sample_app.PermsAutoField', verbose_name='Permissions')),
            ],
            options={
                'db_table': 'user_auto_field',
            },
        ),
        migrations.CreateModel(
            name='ArticleUUIDField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, verbose_name='Perm Label')),
                ('user_uuid_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.UserUUIDField', verbose_name='User')),
            ],
            options={
                'db_table': 'articles_uuid_field',
            },
        ),
        migrations.CreateModel(
            name='ArticleAutoField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Perm Label')),
                ('user_auto_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.UserAutoField', verbose_name='User')),
            ],
            options={
                'db_table': 'articles_auto_field',
            },
        ),
    ]
