# Generated by Django 3.0.6 on 2020-05-28 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFramework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'campaign_frameworks',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CampaignFrameworkPhase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('campaign_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.CampaignFramework')),
            ],
            options={
                'db_table': 'campaign_framework_phases',
                'unique_together': {('campaign_framework', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CampaignFrameworkStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Step Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('layout', models.CharField(max_length=255, verbose_name='HTML')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.CampaignFrameworkPhase', verbose_name='Phase')),
            ],
            options={
                'db_table': 'campaign_framework_steps',
                'unique_together': {('phase', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('campaign_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.CampaignFramework', verbose_name='Campaign Framework')),
            ],
            options={
                'db_table': 'campaigns',
                'unique_together': {('campaign_framework', 'name')},
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='App Name')),
                ('app_desc', models.CharField(max_length=255, verbose_name='App Description')),
                ('data_structure', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Data Structure')),
                ('display_structure', models.TextField(blank=True, null=True, verbose_name='Display Structure')),
            ],
            options={
                'db_table': 'apps',
                'unique_together': {('app_name',)},
            },
        ),
        migrations.CreateModel(
            name='CampaignStepData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('campaign_step_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Campaign Step Data')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.Campaign', verbose_name='Campaign')),
                ('campaign_framework_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.CampaignFrameworkStep', verbose_name='CF Step')),
            ],
            options={
                'db_table': 'campaign_steps',
                'unique_together': {('campaign', 'campaign_framework_step')},
            },
        ),
    ]
