# Generated by Django 3.0.6 on 2020-05-29 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_app_campaign_campaignframework_campaignframeworkphase_campaignframeworkstep_campaignstepdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignframeworkstep',
            old_name='layout',
            new_name='html_layout',
        ),
        migrations.AddField(
            model_name='campaignframeworkstep',
            name='json_layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Campaign Step Data'),
        ),
        migrations.AlterModelTable(
            name='campaignstepdata',
            table='campaign_step_data',
        ),
    ]
