version: '3.7'

services:
  django:
    build: ./services/django
    #image: nodejs
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
      #- ./services/pg_data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django_dev

volumes:
  pg_data:
